version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Build Container
          command: docker build -t spreetail
      - deploy:
          name: Push Docker  image
          command: |
            login="$(aws ecr get-login)"
            ${login}
            docker tag spreetail "${ECR_ENDPOINT}/spreetail:${CIRCLE_SHA1}"
            docker push "${ECR_ENDPOINT}/spreetail:${CIRCLE_SHA1}"
            DATE=$(date +%Y%m%d%H%M)
            if [ "${CIRCLE_BRANCH}" == "dev" ]; then
              docker tag spreetail "${ECR_ENDPOINT}/spreetail:dev${DATE}"
              docker push "${ECR_ENDPOINT}/spreetail:dev${DATE}"
              deploy-dev.sh
            fi
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker tag spreetail "${ECR_ENDPOINT}/spreetail:latest"
              docker push "${ECR_ENDPOINT}/spreetail"
              deploy-prod.sh
            fi