version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - run:
          name: Greeting
          command: docker build .
      - run:
          name: Print the Current Time
          command: date